spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/testdb
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    port: 6379
    host: localhost

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    port: 6379
    host: localhost
  profiles:
    active: test
